---
nodeLinker: node-modules

packageExtensions:
  "@heroui/alert@*":
    peerDependencies:
      framer-motion: "*"
  "@heroui/aria-utils@*":
    peerDependencies:
      framer-motion: "*"
  "@heroui/drawer@*":
    peerDependencies:
      framer-motion: "*"
  "@heroui/number-input@*":
    peerDependencies:
      framer-motion: "*"
  "@heroui/slider@*":
    peerDependencies:
      framer-motion: "*"
  "@heroui/spinner@*":
    peerDependencies:
      framer-motion: "*"
  "@heroui/react@*":
    peerDependencies:
      tailwindcss: "*"
  "@heroui/system@*":
    peerDependencies:
      "@heroui/theme": "*"
  "@heroui/use-aria-accordion@*":
    peerDependencies:
      react-dom: "*"
  "@heroui/use-aria-button@*":
    peerDependencies:
      react-dom: "*"
  "@heroui/use-aria-link@*":
    peerDependencies:
      react-dom: "*"
  "@heroui/use-disclosure@*":
    peerDependencies:
      react-dom: "*"
  "@heroui/use-draggable@*":
    peerDependencies:
      react-dom: "*"
  "@heroui/use-pagination@*":
    peerDependencies:
      react-dom: "*"
  "@sentry/nextjs@*":
    peerDependencies:
      "@opentelemetry/context-async-hooks": "*"
      "@opentelemetry/core": "*"
      "@opentelemetry/sdk-trace-base": "*"
      react: "*"
      webpack: "*"
  "storybook@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
      "@testing-library/dom": "*"
